### ISSUE TITLE
CSV Import says status “completed,” but no results

### ISSUE THREAD

**Issue by jbhistorian** [omeka-s-modules/CSVImport#203] opened 2022-11-03 18:41 UTC
I am experiencing something strange with the CSV Import since Monday. The module was working just fine last week. Now, when I attempt to create records using CSV Import, the job lists Status as “completed,” but no new records are actually created. The Result column is blank. I also tried to run a Revise import job, with the same outcome: Status “completed,” but there’s nothing in the Result column, and the records have not been revised (I checked the records). Plus there is no “Log” link displayed in the Action column as there usually would be.

![image](https://user-images.githubusercontent.com/89092402/199806575-19cc57f3-165f-4ccb-ad3c-f00bd06f74c1.png)

I am running Omeka S version 3.2.0. I was running CSV Import version 2.3.1 when this problem first occurred. I upgraded to CSV Import version 2.3.2 and tried to do an import again, but got the same outcome. The site is https://records.njslavery.org/

I would appreciate any help figuring out what the problem is and fixing it.

**Comment by morarchives** [comment] 2022-11-04 14:26
I am also experiencing this issue.

I am running Omeka S Version 3.2.0 with Reclaim Hosting
CSV Import Module version 2.2.0 worked fine but hadn't used it for a month or so
Then I tried using it for the first time again yesterday to revise items and it would not accept my CSV, got a source format error
Tried using a TSV instead and it accepted it but no log and no changes made
Upgraded to version 2.3.2
It is accepting CSV again but still showing a complete job with no log and no changes to items

Maybe something changed on the server? But since I not hosting myself I no idea where to start looking

Thanks for looking into this;)

**Comment by jbhistorian** [comment] 2022-11-04 14:57
My site is also with Reclaim Hosting.

**Comment by morarchives** [comment] 2022-11-04 15:04
Looks like I need to contact Reclaim Hosting...
Love your site's theme by the way!

**Comment by morarchives** [comment] 2022-11-04 15:25
Maybe it has something to do with this?
Meanwhile my site suddenly stopped loading, so I opened a ticket to get that fixed and will work from there.
![Screenshot 2022-11-04 111721](https://user-images.githubusercontent.com/114703264/200012839-8fd2db63-87bd-4f96-a9dc-9d19c6ca6dd7.png)

**Comment by jbhistorian** [comment] 2022-11-04 15:49
Thank you, it's the Foundation theme.

I think you're right, PHP 8.0 is the problem. I just rolled back to PHP 7.4 using instructions in this article: https://support.reclaimhosting.com/hc/en-us/articles/4405522991255-Changing-Your-PHP-Version-in-cPanel

After rolling back, I was able to run a test revision import (small CVS file with only 2 records), and the records were successfully updated.

**Comment by finantj** [comment] 2022-11-04 17:07
I can confirm that rolling back php to 7.4 seems to have resolved this problem.  I was experiencing the same thing.

**Comment by jbhistorian** [comment] 2022-11-04 21:15
Although rolling back to PHP 7.4 allows the CSV Import module to revise the records, it is no generating a log like it should. So it seems there is still some issue and the module isn't working 100% as expected. See screenshot below. The last successful job before the problem started was on Oct. 28, it shows a link for "Job Details" and a link for "Log." Then there are 8 jobs that didn't yield any results, and then there is the most recent job that worked, listed at the top; it has a link for "Job details," but no link for a "Log."

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/89092402/200075072-428c6172-d07f-43af-a3fe-6c81052539bc.png">

I posted about this problem in the Omeka forums (https://forum.omeka.org/t/csv-import-says-status-completed-but-no-results/15926) and John Flatness from the Omeka Team says that there shouldn't be an incompatibility issue with PHP 8.0, but that "It’s possible that something else about the server setup on 8.0 is changed and that’s causing a problem." I will contact Reclaim Hosting support to see if they can identify any changes that occurred at the same time when they changed to PHP 8.0.

**Comment by jbhistorian** [comment] 2022-11-06 21:06
@morarchives and @finantj I put in a support ticket with Reclaim Hosting about this issue and got a response this morning saying:

"we have just run some apache updates across our servers to ensure better compatibility with PHP 8.0. This was only done today, and there should have been no other major changes besides the switch to PHP 8.0 as the default that could be impacting this."

After receiving this message, I changed PHP for my site to PHP 8.0 and tested the CVS Import module, and it ran successfully. So it seems to be working with PHP 8.0 now.

**Comment by zerocrates** [comment] 2023-02-08 23:20
Tentatively closing this since it seems to be fixed (and possibly not an issue on our end in the first place), but do re-file if an issue reoccurs.

**Closed by zerocrates** 2023-02-08 23:20 UTC
