### ISSUE TITLE
Appending URI values

### ISSUE THREAD

**Issue by jbuwlaw** [omeka-s-modules/CSVImport#189] opened 2021-06-16 16:32 UTC
Hello, it seems that when I try to append URI values it does not work.  The module says the records are updated but they do  not appear updated when I look at the records.  It does work when I revise the records, and the URIs are added as expected.  Perhaps I am not understanding the distinction between the two?  I am using omeka s 3.0.2 and CSV import 2.2.1

**Comment by zerocrates** [comment] 2021-07-07 21:05
Do you have a small test-case CSV/mapping/settings that shows this issue that you can share? That will make it easier to confirm and fix if necessary.

**Comment by jbuwlaw** [comment] 2021-07-08 12:55
Sure.  

I have a comma delimited csv that has 2 columns 'bibo:identifier' and 'customNamespace:customField'.  The data in the first is a unique ID, the second is a URI
On the first import screen:
    - selected the csv file
    - comma delimited
    - double quote enclosure
    - items type
    - automap
    - no comment
On the second screen I set the mapping for the 'customNamespace:customField' to URI data type.  Under the advanced tab I select append and set the resource identifier to 'bibo:identifier'.

This works fine with text data, but when I set it to URI it adds nothing.  Thanks for looking at this!

**Comment by zerocrates** [comment] 2021-09-27 20:22
I can't quite reproduce your problem, but it's possible it's fixed by a recent PR pull which changes how values, particularly URI values, are checked for duplication when doing updates/appends.

Since you're seeing issues only with an append of a URI, I'm thinking this might resolve your problem. The change is on the "develop" branch now.

**Comment by zerocrates** [comment] 2023-08-07 20:13
Going to close this, can always re-file if it's still an issue.

**Closed by zerocrates** 2023-08-07 20:13 UTC
